# Dockerfile for SSL frontend reverse proxy
FROM nginx:stable

# Install Certbot
RUN apt-get update && \
	apt-get install -y aptitude certbot python3-certbot-nginx && \
	rm -rf /var/lib/apt/lists/*

# Copy initial config files (optional if using Docker volumes instead)
COPY ./nginx_default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
